### ISSUE TITLE
Deprecated link from branch name change from master to main in readthedoc

### ISSUE THREAD

**Issue by BCFZzw** [MomentsLD/moments#126]
In [bootstrapping from multiple LDs](https://moments.readthedocs.io/en/main/ld/parsing.html#bootstrapping-over-multiple-regions), the [link to the example in repository](https://bitbucket.org/simongravel/moments/src/master/examples/LD/) is deprecated, possibly due to the name change of the `master` branch to `main`

**Comment by sgravel** [comment]
While at it, we should change hard links from bitbucket to github in the documentation

**Comment by sgravel** [comment]
I fixed the bitbucket hard links in c18e2ada49925049992075e66e75de571bd641e9
