### ISSUE TITLE
The search function is slow or infinite time on the github pages

### ISSUE THREAD

**Issue by sgravel** [MomentsLD/moments#128]
Search worked on readthedocs.

**Comment by General-Solution** [comment]
A surface patch seems to be to load jQuery from an external source (#89a4ffd). Before this jQuery was not being loaded at all; in readthedocs it is loaded from the _static folder. Searching now works but does not load the same results. I will look into loading jQuery from a file and doing so without requiring a separate commit.

**Comment by General-Solution** [comment]
> Searching now works but does not load the same results.

The rtd version loads matching search results from the documentation pages, as well as matches from within moments source code. The gh-pages version only loads results from the documentation pages.
