### ISSUE TITLE
monomorphic sites and theta for a two-epoch model

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [MomentsLD/moments#184]
Hi,

I am using moments to obtain the expected SFS (1D, 20 lineages, folded) for a two-epoch model with parameters, N0, N1 and step, where N0 is Ne in the most recent epoch (with Ne in units of diploid individuals), N1 is Ne is the most ancient epoch, and step is the epoch boundary in units of generations.

I have written the function below to get the expected SFS at a single site, including the proportion of monomorphic sites. 

```
def get_2N_SFS(N0, N1, step, mu):
	theta = mu * N1 * 4
	sfs = moments.Demographics1D.two_epoch((N0 / N1, step / (N1*2)), [20], pop_ids=None).fold() * theta
	sfs[0] = 1 - sum(sfs[1:11]) # monomorphic sites
	return sfs
```

Some initial tests suggest that this is not quite right.

My guess is that I can't simply use `theta = mu * N1 * 4` to rescale the SFS, as the number of segregating sites is determined by all three parameters, not only N1. I saw that it is possible to model mutations at finite sites, thereby obtaining the probability of monomorphic sites too. But, doesn't this still require a value of theta that reflects the number of segregating sites expected for [N0, N1, step]?

Any help would be really appreciated.

Many thanks,

Alex

**Comment by apragsdale** [comment]
Hi Alex - thanks for your question. The infinite sites model implemented in moments (which is the default mutation model) does not provide sensible values for the number of invariant sites, as you've noticed. To get this, I would suggest using the reversible mutation/finite genome model.

For the finite genome model, you can specify forward and backward mutation rates (or provide a single mutation rate, assuming equal forward and backward rates). Note that this is a per-site rate, and should be less than 1. The output SFS will sum to 1, representing the probability of observing allele counts from 0 to n at a given site. If you have some total number of sites `L`, then the total number of invariant sites could be found by `L * sfs[0]`, total number of singletons as `L * sfs[1]`, etc.

A function to simulate this could look something like the following:
```
def two_epoch_reversible(N0, N1, step, mu, n):
    theta = 4 * N1 * mu
    sfs = moments.Spectrum(
        moments.LinearSystem_1D.steady_state_1D_reversible(n, theta), 
        mask_corners=False)
    sfs.integrate([N0 / N1], step / 2 / N1, theta=theta, finite_genome=True)
    sfs = sfs.fold()
    return sfs
```

Let me know if this would work for you or if you have any other questions about it.

**Comment by A-J-F-Mackintosh** [comment]
Hi Aaron,

Many thanks, this is super useful.

I think that

```
moments.LinearSystem_1D.steady_state_1D_reversible(n, theta)
```

should instead be

```
moments.LinearSystem_1D.steady_state_1D_reversible(n, theta_fd=theta, theta_bd=theta)
```

But other than that it seems to work as expected, including giving very similar results to the infinite sites model when mu is small enough.

Thanks again,

Alex
