### ISSUE TITLE
Add moments to pip

### ISSUE THREAD

**Issue by General-Solution** [MomentsLD/moments#91]
**[Original report](https://bitbucket.org/simongravel/moments//issues/91) by Aaron Ragsdale (Bitbucket: [aragsdale](https://bitbucket.org/aragsdale), GitHub: [apragsdale](https://github.com/apragsdale)).**

----------------------------------------

Unfortunately, moments is taken on pypi \([https://pypi.org/project/Moments/](https://pypi.org/project/Moments/)\). Nonetheless, it would still be nice to be able to install from pip. Currently the installation options are to clone and build, run `pip install git+https://bitbucket.org/simongravel/moments.git`, or use conda.

We could perhaps package moments on pypi as `moments-python`, or `moments-sfs` or some other name, so that you could run `pip install moments-python` and then `import moments-python as moments`, at least.

Thoughts, anyone?

**Comment by apragsdale** [comment]
We really should get this on pypi.. (I think) that would mean that wheels for moments are already built and a user doesn't need to compile anything when installing moments. We've run into some issues installing moments from github recently, that this might solve (#165)

**Comment by apragsdale** [comment]
moments is now available on pypi: https://pypi.org/project/moments-popgen/

`pip install moments-popgen` will install.

Then
```
python -c "import moments;print(moments.__version__)"
```
to check that it worked.
